<script src="{{asset('backend_assets/js/jquery-3.3.1.min.js')}}"></script>
<script>window.jQuery || document.write('<script src="src/js/vendor/jquery-3.3.1.min.js><\/script>')</script>
<script src="{{asset('backend_assets/plugins/popper.js/dist/umd/popper.min.js')}}"></script>
<script src="{{asset('backend_assets/plugins/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<script src="{{asset('backend_assets/plugins/perfect-scrollbar/dist/perfect-scrollbar.min.js')}}"></script>
<script src="{{asset('backend_assets/plugins/screenfull/dist/screenfull.js')}}"></script>
<script src="{{asset('backend_assets/plugins/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('backend_assets/plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('backend_assets/plugins/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('backend_assets/plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js')}}"></script>
<script src="{{asset('backend_assets/plugins/jvectormap/jquery-jvectormap.min.js')}}"></script>
<script src="{{asset('backend_assets/plugins/d3/dist/d3.min.js')}}"></script>
<script src="{{asset('backend_assets/plugins/c3/c3.min.js')}}"></script>
<script src="{{asset('backend_assets/js/tables.js')}}"></script>
<script src="{{asset('backend_assets/js/widgets.js')}}"></script>
<script src="{{asset('backend_assets/js/charts.js')}}"></script>
<script src="{{asset('backend_assets/dist/js/theme.min.js')}}"></script>
<script src="{{asset('backend_assets/src/js/vendor/modernizr-2.8.3.min.js')}}"></script>