<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700,800" rel="stylesheet"> 
<link rel="stylesheet" href="{{asset('backend_assets/plugins/bootstrap/dist/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('backend_assets/plugins/fontawesome-free/css/all.min.css')}}">
<link rel="stylesheet" href="{{asset('backend_assets/plugins/icon-kit/dist/css/iconkit.min.css')}}">
<link rel="stylesheet" href="{{asset('backend_assets/plugins/ionicons/dist/css/ionicons.min.css')}}">
<link rel="stylesheet" href="{{asset('backend_assets/plugins/perfect-scrollbar/css/perfect-scrollbar.css')}}">
<link rel="stylesheet" href="{{asset('backend_assets/plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('backend_assets/plugins/jvectormap/jquery-jvectormap.css')}}">
<link rel="stylesheet" href="{{asset('backend_assets/plugins/tempusdominus-bootstrap-4/build/css/tempusdominus-bootstrap-4.min.css')}}">
<link rel="stylesheet" href="{{asset('backend_assets/plugins/weather-icons/css/weather-icons.min.css')}}">
<link rel="stylesheet" href="{{asset('backend_assets/plugins/c3/c3.min.css')}}">
<link rel="stylesheet" href="{{asset('backend_assets/plugins/owl.carousel/dist/assets/owl.carousel.min.css')}}">
<link rel="stylesheet" href="{{asset('backend_assets/plugins/owl.carousel/dist/assets/owl.theme.default.min.css')}}">
<link rel="stylesheet" href="{{asset('backend_assets/dist/css/theme.min.css')}}">